let data, selectedMood=null, calendarDate=new Date(); const $=s=>document.querySelector(s), $$=s=>document.querySelectorAll(s);
const moods={happy:{name:"Happy",emoji:"😊",text:"Ada hal baik yang sedang kamu rasakan hari ini.",care:["🎧 Dengarkan musik favorit","📸 Simpan momen kecil","💬 Ceritakan kabar baik ke orang terdekat"]},calm:{name:"Calm",emoji:"😌",text:"Kamu terlihat sedang menikmati suasana yang tenang.",care:["📖 Baca beberapa halaman","🌿 Nikmati udara segar","🫖 Buat minuman hangat"]},excited:{name:"Excited",emoji:"🤩",text:"Energi positifmu lagi tinggi! Nikmati momennya.",care:["🎨 Coba aktivitas kreatif","📋 Tulis hal yang ingin dilakukan","🎶 Putar playlist favorit"]},neutral:{name:"Neutral",emoji:"😐",text:"Hari biasa juga tetap berarti.",care:["🚶 Jalan santai","🧹 Rapikan satu sudut kamar","🧩 Kerjakan hal kecil yang menyenangkan"]},tired:{name:"Tired",emoji:"😴",text:"Mungkin tubuh dan pikiranmu butuh jeda.",care:["🛌 Istirahat sejenak","💧 Minum air","📵 Kurangi screen time sebentar"]},sad:{name:"Sad",emoji:"😔",text:"Nggak apa-apa punya hari yang terasa berat.",care:["📝 Tulis apa yang kamu rasakan","🤝 Cari teman/orang dewasa yang kamu percaya","🌤️ Cari tempat yang terasa nyaman"]},anxious:{name:"Anxious",emoji:"😟",text:"Coba pelan-pelan dan fokus pada hal yang bisa kamu lakukan sekarang.",care:["🌬️ Tarik napas perlahan","🧸 Lakukan aktivitas yang familiar","🗒️ Pecah tugas besar jadi langkah kecil"]}};
const fallback={entries:[],journal:[{title:"A tiny good moment",date:"Contoh",icon:"🌷",text:"Hari ini aku menyadari bahwa momen kecil juga bisa membuat hari terasa lebih baik."},{title:"A quiet afternoon",date:"Contoh",icon:"☁️",text:"Simpan cerita sederhana di sini. Kamu bisa menulis apa pun yang ingin kamu ingat."}],quotes:["You don't have to have it all figured out today.","Small progress is still progress.","Take it one moment at a time.","Your feelings are worth listening to.","A soft day is still a good day."],selfcare:[]};
async function init(){try{let r=await fetch("data.json");data=await r.json()}catch(e){data=fallback}let saved=localStorage.getItem("moodify");if(saved)try{data=JSON.parse(saved)}catch(e){}render();todayDate();calendar()}
function save(){localStorage.setItem("moodify",JSON.stringify(data));render();toast("Saved ✨")}
function todayKey(d=new Date()){return d.toISOString().slice(0,10)}
function render(){home();checkin();stats();journal();selfcare();calendar()}
function home(){let e=data.entries.find(x=>x.date===todayKey());$("#homeMood").textContent=e?moods[e.mood].emoji:"—";$("#homeMoodName").textContent=e?moods[e.mood].name:"Not checked in yet";$("#homeMoodText").textContent=e?(e.note||moods[e.mood].text):"Yuk pilih mood kamu hari ini.";$("#quote").textContent=data.quotes[new Date().getDate()%data.quotes.length];let days=[];for(let i=6;i>=0;i--){let d=new Date();d.setDate(d.getDate()-i);let e2=data.entries.find(x=>x.date===todayKey(d));days.push(`<div class="week-day"><small>${d.toLocaleDateString("en-US",{weekday:"short"})}</small><div>${e2?moods[e2.mood].emoji:"·"}</div></div>`)}$("#weekMoods").innerHTML=days.join("")}
function todayDate(){$("#todayDate").textContent=new Date().toLocaleDateString("id-ID",{day:"numeric",month:"long",year:"numeric"})}
function checkin(){$("#moodGrid").innerHTML=Object.entries(moods).map(([key,m])=>`<button class="mood-option ${selectedMood===key?"selected":""}" data-mood="${key}"><span class="emoji">${m.emoji}</span><small>${m.name}</small></button>`).join("");$("#intensityValue").textContent=$("#intensity").value+" / 5";let e=data.entries.find(x=>x.date===todayKey());if(e&&!selectedMood){selectedMood=e.mood;$("#checkNote").value=e.note||"";$("#intensity").value=e.intensity||3;$("#intensityValue").textContent=$("#intensity").value+" / 5";$("#moodGrid").innerHTML=Object.entries(moods).map(([key,m])=>`<button class="mood-option ${selectedMood===key?"selected":""}" data-mood="${key}"><span class="emoji">${m.emoji}</span><small>${m.name}</small></button>`).join("")}}
function stats(){let entries=data.entries||[];$("#checkinsCount").textContent=entries.length;let avg=entries.length?(entries.reduce((a,x)=>a+(+x.intensity||0),0)/entries.length).toFixed(1):"0";$("#avgIntensity").textContent=avg+"/5";let count={};entries.forEach(e=>count[e.mood]=(count[e.mood]||0)+1);let top=Object.entries(count).sort((a,b)=>b[1]-a[1])[0];$("#dominantEmoji").textContent=top?moods[top[0]].emoji:"—";$("#dominantName").textContent=top?moods[top[0]].name:"No data yet";$("#dominantText").textContent=top?`${top[1]} check-in${top[1]>1?"s":""} — mood yang paling sering muncul.`:"Mulai check-in untuk melihat statistik.";let max=Math.max(1,...Object.values(count));$("#moodBars").innerHTML=Object.entries(moods).map(([k,m])=>{let n=count[k]||0;return `<div class="bar-row"><div class="bar-top"><span>${m.emoji} ${m.name}</span><b>${n}</b></div><div class="bar-track"><span style="width:${n/max*100}%"></span></div></div>`}).join("")}
function calendar(){let y=calendarDate.getFullYear(),m=calendarDate.getMonth(),first=new Date(y,m,1),last=new Date(y,m+1,0);$("#monthName").textContent=first.toLocaleDateString("en-US",{month:"long",year:"numeric"});let cells=[];for(let i=0;i<first.getDay();i++)cells.push(`<div class="cal-day muted"></div>`);for(let d=1;d<=last.getDate();d++){let date=new Date(y,m,d),key=todayKey(date),e=data.entries.find(x=>x.date===key),today=key===todayKey();cells.push(`<div class="cal-day ${today?"today":""}"><div class="num">${d}</div><div class="mood">${e?moods[e.mood].emoji:""}</div></div>`)}$("#calendarGrid").innerHTML=cells.join("");$("#legend").innerHTML=Object.values(moods).map(x=>`<span>${x.emoji} ${x.name}</span>`).join("")}
function journal(){let arr=data.journal||[];$("#journalGrid").innerHTML=arr.map((x,i)=>`<article class="journal-card"><div class="journal-icon">${x.icon}</div><h3>${x.title}</h3><p>${x.text}</p><small>${x.date}</small></article>`).join("")}
function selfcare(){let all=[];Object.values(moods).forEach(m=>m.care.forEach((x,i)=>all.push({icon:x.slice(0,2),text:x.slice(2).trim(),mood:m.name})));$("#selfcareGrid").innerHTML=all.slice(0,9).map(x=>`<article class="care-card"><div class="care-icon">${x.icon}</div><h3>${x.text}</h3><p>Suggested for ${x.mood} days.</p></article>`).join("")}
function page(id){$$(".page").forEach(x=>x.classList.toggle("active",x.id===id));$$(".nav").forEach(x=>x.classList.toggle("active",x.dataset.page===id));$("#pageTitle").textContent={home:"Home",checkin:"Mood Check-in",calendar:"Mood Calendar",stats:"Statistics",journal:"Journal",selfcare:"Self-care"}[id];$("#sidebar").classList.remove("open")}
function toast(t){let x=$("#toast");x.textContent=t;x.classList.add("show");setTimeout(()=>x.classList.remove("show"),1700)}
function openJournal(){ $("#modalContent").innerHTML=`<h2>New Journal Entry ✎</h2><form class="form" id="journalForm"><input name="title" placeholder="Judul cerita..." required><input name="icon" value="🌷"><textarea name="text" placeholder="Ceritakan sedikit tentang hari kamu..." required></textarea><button class="primary">Save memory</button></form>`;$("#modal").classList.add("show");$("#journalForm").onsubmit=e=>{e.preventDefault();let f=new FormData(e.target);data.journal.unshift({title:f.get("title"),date:new Date().toLocaleDateString("id-ID",{day:"numeric",month:"long",year:"numeric"}),icon:f.get("icon"),text:f.get("text")});save();closeModal()}}
function closeModal(){$("#modal").classList.remove("show")}
document.addEventListener("click",e=>{let p=e.target.closest("[data-page]");if(p)page(p.dataset.page);let m=e.target.closest("[data-mood]");if(m){selectedMood=m.dataset.mood;checkin()}if(e.target.id==="saveMood"){if(!selectedMood){toast("Pilih mood dulu ya ♡");return}let entry={date:todayKey(),mood:selectedMood,intensity:+$("#intensity").value,note:$("#checkNote").value.trim()};let idx=data.entries.findIndex(x=>x.date===entry.date);if(idx>=0)data.entries[idx]=entry;else data.entries.push(entry);save();toast("Today's mood saved ✨");page("home")}if(e.target.id==="newJournal")openJournal();if(e.target.id==="closeModal"||e.target.id==="modal")closeModal();if(e.target.id==="prevMonth"){calendarDate.setMonth(calendarDate.getMonth()-1);calendar()}if(e.target.id==="nextMonth"){calendarDate.setMonth(calendarDate.getMonth()+1);calendar()}});
$("#intensity").addEventListener("input",()=>$("#intensityValue").textContent=$("#intensity").value+" / 5");
function toggleTheme(){document.documentElement.classList.toggle("dark");localStorage.setItem("moodifyTheme",document.documentElement.classList.contains("dark")?"dark":"light")}
$("#themeBtn").onclick=toggleTheme;$("#topTheme").onclick=toggleTheme;$("#menuBtn").onclick=()=>$("#sidebar").classList.toggle("open");if(localStorage.getItem("moodifyTheme")==="dark")document.documentElement.classList.add("dark");init();